### ISSUE TITLE
yapf --style=pep8 continuation line may not distinguish itself from next line

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#21]
The following code:

    class Foo(object):

        def bar(self):
            if self.solo_generator is None and len(
                    self.generators + self.next_batch) == 1:
                pass

reformats as

    class Foo(object):
        def bar(self):
            if self.solo_generator is None and len(
                self.generators + self.next_batch) == 1:
                pass

Which the pep8 error checker says "E125 continuation line with same indent as next logical line" to

**Comment by DRMacIver** [comment]
Confirmed in master.

**Comment by hayd** [comment]
Should CONTINUATION_INDENT_WIDTH=8 ?
```
yapf foo.py --style="{based_on_style: pep8, CONTINUATION_INDENT_WIDTH: 8}"
class Foo(object):
    def bar(self):
        if self.solo_generator is None and len(
                self.generators + self.next_batch) == 1:
            pass
```
This seems to pass pep8.

**Comment by gwelymernans** [comment]
@hayd So if I understand what you're saying, if the next line is indented to the same amount as this indentation, then we need to increase the indentation by `CONTINUATION_INDENT_WIDTH`? Maybe something like:

```
self.stack[-1].closing_scope_indent = max(
          0, self.stack[-1].indent - style.Get('CONTINUATION_INDENT_WIDTH'))
if next_uwline is indented and closing_scope_indent == indentation_amount:  # (Pseudocode)
  self.stack[-1].closing_scopt_indent += style.Get('CONTINUATION_INDENT_WIDTH')
```

What do you think?

**Comment by hayd** [comment]
That looks correct. (assuming a tiny column width) I think this is what pep8's looking for:

```
(not "indenting" +
    "continued")

if ("indenting" +
        "continued"):
    "single indent"
```

**Comment by gwelymernans** [comment]
Okay. I'll take a look at this soon. I think that there are a few PRs open that are similar to this one...

**Comment by alexjurkiewicz** [comment]
Bites me too. Here's a simpler example:

yapf:

    if aaaaaaaaaaaaa(
        'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        'cccccccccccccccccccccccccccccccccccccccccccc'):
        pass

desired:

    if aaaaaaaaaaaaa(
        'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
            'cccccccccccccccccccccccccccccccccccccccccccc'):
        pass

**Comment by gwelymernans** [comment]
I think this has been addressed now. Please take a look.

**Comment by alexjurkiewicz** [comment]
:+1: !

**Comment by joaoportela** [comment]
I'm having the same issue, is this fixed in version 0.3.1?

    $ yapf --version
    yapf 0.3.1

    $ yapf datasync/server.py --diff
    --- datasync/server.py  (original)
    +++ datasync/server.py  (reformatted)
    @@ -82,7 +82,7 @@
    def validate_message_structure(message):
        """Check if the message contains all keys."""
        if ("op" in message and "args" in message and "api" in message and
    -            "orig" in message):
    +        "orig" in message):
            return True
        else:
            return False

**Comment by tschaub** [comment]
It looks to me like this is still an issue when `dedent_closing_brackets: true` is used.

This code aligns with PEP 8 recommendations:
```py
if (
    0X000000000000000000000000 and 0X000000000000000000000000
) or (
    0X000000000000000000000000 and 0X000000000000000000000000
):
    pass
```

Passing it through `yapf --style "{based_on_style: pep8, dedent_closing_brackets: true}" check.py` yields this:
```py
if (0X000000000000000000000000 and 0X000000000000000000000000
    ) or (0X000000000000000000000000 and 0X000000000000000000000000):
    pass
```

Which doesn't align with PEP 8's [indentation recommendation](https://www.python.org/dev/peps/pep-0008/#indentation) 
 and raises flake8's "continuation line with same indent as next logical line" E125 error.
